import type { Metadata } from "next";
import { Source_Code_Pro } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const sourceCodePro = Source_Code_Pro({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Afzal Khan - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceCodePro.className} antialiased bg-bgprimary`}
      >
        <div className="w-[90vw] md:w-[900px] h-fit mx-auto flex flex-col justify-start items-start">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
